[package]
name = "ic-agent"
version = "0.12.1"
authors = ["DFINITY Stiftung <sdk@dfinity.org>"]
edition = "2018"
description = "Agent library to communicate with the Internet Computer, following the Public Specification."
homepage = "https://docs.rs/ic-agent"
documentation = "https://docs.rs/ic-agent"
license = "Apache-2.0"
readme = "README.md"
categories = ["api-bindings", "data-structures", "no-std"]
keywords = ["internet-computer", "agent", "icp", "dfinity"]
include = ["src", "Cargo.toml", "../LICENSE", "README.md"]

[dependencies]
libc = "0.2"
jni = { version = "0.5.1", optional = true, default-features = false }
async-trait = "0.1.51"
base32 = "0.4.0"
base64 = "0.13.0"
byteorder = "1.3.2"
garcon = { version = "0.2", features = ["async"] }
hex = "0.4.0"
http = "0.2.6"
hyper-rustls = { version = "0.23.0", features = [ "webpki-roots" ] }
ic-types =  {git = "https://github.com/FirstFieldGmbH/ic-types.git", rev = "948709c5d7fd8b128abfdae0bb3f21ca57e0140b" }
leb128 = "0.2.5"
mime = "0.3.16"
rand = "0.8.4"
openssl = {version = "0.10.38", features = ["vendored"]}
rustls = "0.20.2"
ring = { version = "0.16.11", features = ["std"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_bytes = "0.11.2"
serde_cbor = "0.11.2"
serde_json = "1.0.74"
simple_asn1 = "0.6.1"
thiserror = "1.0.30"
url = "2.1.0"

[dependencies.reqwest]
version = "0.11"
features = [ "blocking", "json", "rustls-tls" ]
optional = true

[dependencies.pem]
version = "1.0"
optional = true

[dev-dependencies]
candid = "0.7.10"
mockito = "0.30.0"
proptest = "1.0.0"
tokio = { version = "1.15.0", features = ["full"] }

[features]
default = ["jni", "pem", "reqwest"]
ic_ref_tests = ["default"] # Used to separate integration tests for ic-ref which need a server running.

[lib]
name = "ic_agent_lib"
crate-type = ["staticlib", "cdylib"]
