name: Linter

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm set //npm.pkg.github.com/:_authToken=${{ secrets.PACKAGE_TOKEN }} && npm set @Psychedelic:registry=https://npm.pkg.github.com/ && yarn

    - name: Run ESLint
      run: yarn lint
