name: Linter

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc && yarn
      env:
        GITHUB_TOKEN: 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

    - name: Audit
      run: yarn audit

    - name: Run ESLint
      run: yarn lint
